version: 2
models:
  - name: fct_crypto_hourly
    tags: ["hourly", "silver"]
    # tests:
      # - dbt_utils.expression_is_true:
      #     expression: 'high >= low'
      # - dbt_utils.expression_is_true:
      #     expression: 'high >= open'
      # - dbt_utils.expression_is_true:
      #     expression: 'high >= close'
      # - dbt_utils.expression_is_true:
      #     expression: 'low <= open'
      # - dbt_utils.expression_is_true:
      #     expression: 'low <= close'
    columns:
      - name: time
        description: Calendar date and hour
        tests:
          - unique
          - not_null
          - dbt_utils.sequential_values:
              interval: 1
              datepart: 'hour'
      - name: high
        description: Cryptocurrency highest value reached during the hour
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'

      - name: low
        description: Cryptocurrency lowest value reached during the hour
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: open
        description: Cryptocurrency value at the beginning of the day
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: close
        description: Cryptocurrency value at the end of the day
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: volume_from
        description: Volume of crypto exchanged during the hour
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: volume_to
        description: Volume of crypto exchanged during the hour in local currency (i.e EUR, USD)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'